/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_test_CppConfig */

#ifndef _Included_com_test_CppConfig
#define _Included_com_test_CppConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_CppConfig
 * Method:    setConfiguration
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_CppConfig_setConfiguration
(JNIEnv *, jobject);

/*
 * Class:     com_test_CppConfig
 * Method:    setConfigCase0
 * Signature: (Lcom/config/ConfigTti;)V
 */
//JNIEXPORT void JNICALL Java_com_test_CppConfig_setConfigCase0
  //(JNIEnv *, jobject, jobject);

/*
 * Class:     com_test_CppConfig
 * Method:    setConfigCase1
 * Signature: (Lcom/config/ConfigTti;I)V
 */
JNIEXPORT void JNICALL Java_com_test_CppConfig_setConfigCase1
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_test_CppConfig
 * Method:    setConfigCase2
 * Signature: (Lcom/config/ConfigTti;Ljava/lang/String;)V
 */
//JNIEXPORT void JNICALL Java_com_test_CppConfig_setConfigCase2
  //(JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
